#!/bin/bash

source .pre-run
source .pre-update
require_svn

$svn update

source .post-update

echo
echo ________________________________________________________________________________
echo if any lines begin with "C", then please resolve the conflict.
echo otherwise you can run ./10-edit-hosts
