#!/bin/bash

cd `dirname $0`

python=`which python`
if [ "x$python" == "x" ]; then
  echo Error: python not in path
elif [ "$python" == "/opt/pub/bin/python" ]; then
  echo Warning: setting path in hopes of circumventing PIRL python build
  export PATH=/usr/sfw/bin:/usr/bin:$PATH
fi
# which python
./editor/bin/add.py "$@"

(cd res/db;xsltproc tests/syntax.xsl host_list.xml)

echo If no errors were reported, please run ./30-update-zones
