#!/bin/bash

source .pre-run
require_svn

echo Please review changes for problems.
$svn diff \
	res/db/host_list.xml \
	dhcp_area/tables/{ipv4,ipv6}* \
	views/*/{named.conf,extra-reverse.conf,zones}

echo
echo If all changes look fine, please run ./60-commit-changes

